server:
  tomcat:
    uri-encoding: UTF-8
  port: 18080
  servlet:
    context-path: /bingo
    session:
      cookie:
        http-only: true

spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.bingo.modules.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false
